name: Push Develop Branch â­ï¸

on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  contents: write
  actions: write

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code ğŸƒâ€â¡ï¸
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up Git User ğŸ§‘â€ğŸ’»
        run: |
          git config --global user.name "AlkongDalkong"
          git config --global user.email "alkongd29@gmail.com"

      - name: Add remote repository ğŸŒ
        run: git remote add target https://${{ secrets.PUSH_TOKEN }}@github.com/AlkongDalkong/alkong-dalkong_fe.git

      - name: Push develop to develop ğŸš€
        run: git push target develop:develop
