name: Push Develop Branch ğŸ”¨

on:
  push:
    branches:
      - develop

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code ğŸƒâ€â¡ï¸
        uses: actions/checkout@v3

      - name: Set up Git User ğŸ§‘â€ğŸ’»
        run: |
          git config --global user.name "AlkongDalkong"
          git config --global user.email "alkongd29@gmail.com"

      - name: Set destination repo ğŸŒˆ
        run: git remote add destination-repo https://$GITHUB_ACTOR:${{ secrets.PUSH_TOKEN }}@github.com/AlkongDalkong/alkong-dalkong_fe.git

      - name: Push develop to develop ğŸš€
        run: git push destination-repo develop:develop
