name: Push Main Branch ğŸ 

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  Push-Alkong-Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code ğŸƒâ€â¡ï¸
        uses: actions/checkout@v2

      - name: Set up Git User ğŸ§‘â€ğŸ’»
        run: |
          git config --global user.name "AlkongDalkong"
          git config --global user.email "alkongd29@gmail.com"

      - name: Set destination repo ğŸŒˆ
        run: git remote add destination-repo https://github.com/AlkongDalkong/alkong-dalkong_fe.git

      - name: Push main to main ğŸš€
        run: git push destination-repo main:main